---
title: "corona_analysis"
output:
  html_document:
    fig_width: 6
    fig_height: 4

knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file, 
  encoding=encoding,
  output_file=here::here(out_dir,"index2.html")
 )
 })
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  collapse = TRUE,
  comment = "#>",
  rownames.print = 60,
  cols.print=40)

```

```{r, echo=FALSE, warning=FALSE}
require(pacman)
p_load(tidyverse)
p_load(lubridate)
p_load(magrittr)
p_load(fpp3)
p_load(plotly)
p_load(slider)
p_load(glue)
p_load(hrbrthemes)
```

# CONFIG
```{r}

countries_of_interest <- 
  list(
    "S. Korea", #"Korea, South",
    "Spain", 
    "Italy" ,
    "Norway",
    "Israel", 
    "France",
    "Switzerland", 
    "Sweden",
    "Germany",
    "Netherlands", 
    "UK"
  )


```


```{r}
df <- 
  read_csv("./data/daily_records_worldmeters.csv") %>% 
  select(
    country = Country,
    date = Date,
    confirmed = `Total Cases`,
    critical = Critical,
    recovered = `Total Recovered`,
    death = `Total Deaths`
  ) %>% 
  mutate(
    date = as.Date(date,"%d-%m-%Y"),
  ) %>% 
  group_by(country) %>% 
  arrange(date) %>% 
  mutate(
    active = confirmed - recovered - death,
    new_cases = pmax(confirmed - lag(confirmed),0),
    r_lag_critical = lag(critical),
    r_critical = critical/lag(critical),
    r_critical = ifelse(is.infinite(r_critical) | is.nan(r_critical) | is.na(r_critical), 1, r_critical),
    r_active = active/lag(active),
    r_active = ifelse(is.infinite(r_active) | is.nan(r_active) | is.na(r_active), 1, r_active),
    nday = difftime(date, min(date), units = "days") %>% as.integer() 
) %>% 
  ungroup() %>% 
   arrange(country,date) 


tf <- 
  df %>% 
  filter(country %in% countries_of_interest) %>% 
  as_tsibble(key = country, index = date)

# df %>% filter(country == "France") %>% view

```




```{r}

data_for_plot <-
  tf %>% 
  group_by(country) %>% 
  filter(date >= min(date[active>=1])) %>%  
  mutate(nday = difftime(date, min(date), units = "days") %>% as.integer()) %>% 
  ungroup() 
```


# active & critical vs time (log scale)
```{r, fig.width=11, fig.height=6}
  data_for_plot %>% 
  ggplot(aes(x = nday, color = country)) +
  geom_line(aes(y = log(critical))) +
  geom_line(aes(y = log(active))) +
  ylab("active & critical (log scale")+
  ggtitle("log(active) & log(critical) vs. time")+
  facet_wrap(~country, scales = "free_x")
```


# optimal lag between active and critical
```{r}


# active slove vs. critical slope: active-lag(active,1) vs. critical-lag(critical
local({
ccf_active_critival_new_cases <-
  data_for_plot %>%
  update_tsibble(index = nday) %>%
CCF(active-lag(active,1), critical-lag(critical,1))

ccf_active_critival_new_cases %>% autoplot()

ccf_active_critival_new_cases %>%
  filter(abs(lag)<=14) %>%
  group_by(country) %>%
  filter(ccf == max(ccf) & abs(max(ccf))>=0.1) %>%
  arrange(desc(ccf)) %>%
  mutate(ccf = round(ccf,2))
})


# active r vs. critical r
local({
  ccf_active_critival <- 
    data_for_plot %>% 
    update_tsibble(index = nday) %>% 
    CCF(r_active, r_critical)
  
  ccf_active_critival %>% 
    autoplot()
  
  ccf_active_critival %>% 
    filter(abs(lag)<=14) %>% 
    group_by(country) %>% 
    arrange(desc(ccf)) %>% 
    mutate(ccf_round = round(ccf,2)) %>% 
    arrange(lag) %>% 
    filter(lag<0, ccf>0.1) %>% 
    pivot_wider(country,names_from=lag,
                values_from = ccf_round)
  # 
  # z %>% 
  #   filter(lag<0) %>%
  #   group_by(country) %>% 
  #   mutate(ccf_normalized = ccf/max(abs(ccf))) %>% 
  #   ungroup() %>% 
  #   ggplot(aes(x=lag, y=country, fill = ccf/ccf_normalized))+
  #   geom_tile()+
  #   scale_fill_gradient(low="white", high="blue") +
  # theme_ipsum()
    
})




#  cdf by  optimal lag - note the lag =  -12  zon
local({
    data_for_plot %>% 
    update_tsibble(index = nday) %>% 
    CCF(r_active, r_critical) %>% 
    arrange(country, lag) %>% 
    mutate(ccf = round(ccf,2)) %>% 
    group_by(country) %>% 
    slice(max(0,which.max(ccf)-3): max(0,which.max(ccf)+3))
})



# max lag  = -2 ==> active precedes critical by 2.
# tibble(
#   day = 1:9,
#   active = c( 0,  1, 2,3,-4,-5,6,NA,NA),
#   critcal = c(NA, NA,0,1, 2, 3,-4,-5,6)
# ) %>%
#   as_tsibble(index = day) %>%
#   CCF(active,critcal) %>% 
#   arrange(desc(ccf))


```


# r_active & r_critical vs time
```{r, fig.width=11, fig.height=6}
  data_for_plot %>% 
  ggplot(aes(x = nday)) +
  geom_line(aes(y = r_critical, color = "critical")) +
  geom_line(aes(y = r_active, color = "active")) +
  # ylab("active & critical (log scale")+
  ggtitle("active rate & critical rate vs. time")+
  ylim(0,2)+
  # guides(color=guide_legend(title="patient type - red - critical, green - active")) +
  facet_wrap(~country, scales = "free")
```


# % active vs. time
```{r, fig.width=11, fig.height=6}

OPT_ACTIVE_CRITICAL_LAG <- 7

tf_enriched <- 
  tf %>% 
  update_tsibble(index = nday) %>% 
  group_by(country) %>% 
  filter(date >= min(date[active>=1])) %>%  
  arrange(date) %>% 
  mutate(r_active_lag = lag(active, OPT_ACTIVE_CRITICAL_LAG),
         lag_active = lag(active, OPT_ACTIVE_CRITICAL_LAG),
         prc_critical_active_lagged = 100*critical/lag_active,
         prc_critical_active_lagged = ifelse(is.infinite(prc_critical_active_lagged) | is.nan(prc_critical_active_lagged) | is.na(prc_critical_active_lagged), 0, prc_critical_active_lagged) %>% pmax(0) %>% pmin(100)
         ) %>% 
  ungroup()

(tf_enriched %>% 
  ggplot(aes(x=nday, 
             y=round(prc_critical_active_lagged,2), 
             critical = critical,
             lag_active = lag_active,
             active = active,
             
             color = country)) + 
  geom_line() +
    ggtitle("Convertion rate - % critcal out of active (7 day lag)")+
  # theme(legend.position='none')+
  facet_wrap(~country, scales = "free_x")) %>% 
  ggplotly




```



